name: tensorflow
channels:
  - defaults
dependencies:
  - _tflow_select=2.1.0=gpu
  - absl-py=0.8.0=py37_0
  - astor=0.8.0=py37_0
  - autopep8=1.4.4=py_0
  - blas=1.0=mkl
  - ca-certificates=2019.10.16=0
  - certifi=2019.9.11=py37_0
  - cudatoolkit=10.0.130=0
  - cudnn=7.6.0=cuda10.0_0
  - cycler=0.10.0=py37_0
  - freetype=2.9.1=ha9979f8_1
  - gast=0.2.2=py37_0
  - google-pasta=0.1.7=py_0
  - grpcio=1.16.1=py37h351948d_1
  - h5py=2.9.0=py37h5e291fa_0
  - hdf5=1.10.4=h7ebc959_0
  - icc_rt=2019.0.0=h0cc432a_1
  - icu=58.2=ha66f8fd_1
  - intel-openmp=2019.4=245
  - joblib=0.14.0=py_0
  - jpeg=9b=hb83a4c4_2
  - keras-applications=1.0.8=py_0
  - keras-preprocessing=1.1.0=py_1
  - kiwisolver=1.1.0=py37ha925a31_0
  - libpng=1.6.37=h2a8f88b_0
  - libprotobuf=3.9.2=h7bd577a_0
  - libtiff=4.1.0=h56a325e_0
  - markdown=3.1.1=py37_0
  - matplotlib=3.1.1=py37hc8f65d3_0
  - mkl=2019.4=245
  - mkl-service=2.3.0=py37hb782905_0
  - mkl_fft=1.0.14=py37h14836fe_0
  - mkl_random=1.1.0=py37h675688f_0
  - numpy=1.17.2=py37hc73f44b_0
  - numpy-base=1.17.2=py37hc3f5095_0
  - olefile=0.46=py37_0
  - openssl=1.1.1d=he774522_3
  - opt_einsum=3.1.0=py_0
  - pillow=6.2.1=py37hdc69c19_0
  - pip=19.3.1=py37_0
  - protobuf=3.9.2=py37h33f27b4_0
  - pycodestyle=2.5.0=py37_0
  - pyparsing=2.4.2=py_0
  - pyqt=5.9.2=py37h6538335_2
  - pyreadline=2.1=py37_1
  - python=3.7.5=h8c8aaf0_0
  - python-dateutil=2.8.0=py37_0
  - pytz=2019.3=py_0
  - qt=5.9.7=vc14h73c81de_0
  - scikit-learn=0.21.3=py37h6288b17_0
  - scipy=1.3.1=py37h29ff71c_0
  - setuptools=41.6.0=py37_0
  - sip=4.19.8=py37h6538335_0
  - six=1.12.0=py37_0
  - sqlite=3.30.1=he774522_0
  - tensorboard=2.0.0=pyhb230dea_0
  - tensorflow=2.0.0=gpu_py37h57d29ca_0
  - tensorflow-base=2.0.0=gpu_py37h390e234_0
  - tensorflow-estimator=2.0.0=pyh2649769_0
  - tensorflow-gpu=2.0.0=h0d30ee6_0
  - termcolor=1.1.0=py37_1
  - tk=8.6.8=hfa6e2cd_0
  - tornado=6.0.3=py37he774522_0
  - vc=14.1=h0510ff6_4
  - vs2015_runtime=14.16.27012=hf0eaf9b_0
  - webencodings=0.5.1=py37_1
  - werkzeug=0.16.0=py_0
  - wheel=0.33.6=py37_0
  - wincertstore=0.2=py37_0
  - wrapt=1.11.2=py37he774522_0
  - xz=5.2.4=h2fa13f4_4
  - zlib=1.2.11=h62dcd97_3
  - zstd=1.3.7=h508b16e_0
prefix: C:\Development\Anaconda3\envs\tensorflow

